version: '3'

services:
  selenoid:
    container_name: selenoid
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [
      "-conf", "/etc/selenoid/browsers.json", 
      "-service-startup-timeout", "10m0s",
      "-session-attempt-timeout", "10m0s",
      "-session-delete-timeout", "10m0s",
      "-timeout", "10m0s"
      ]
    ports:
      - "4444:4444"